kind: Service
apiVersion: v1
metadata:
  name: balancer-service
  labels:
    app: caporderack
spec:
  selector:
    app: caporderack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
